/* Generated by packages/shared/vite/swPlugin.js. Do not edit. */
const CACHE_NAME = "life-architecture-d2d4891a";
const CACHE_PREFIX = "life-architecture-";
// Large cache-only files (engine nets, game databases) live in a cache that
// survives deploys; only the per-build cache is replaced on activate.
const DATA_CACHE = CACHE_PREFIX + "data";
const INDEX_URL = new URL("/life-architecture/index.html", self.location).href;
const SCOPE_PATH = new URL(self.registration.scope).pathname;
const PRECACHE = [
  "/life-architecture/",
  "/life-architecture/index.html",
  "/life-architecture/manifest.json",
  "/life-architecture/icon-192.png",
  "/life-architecture/icon-512.png",
  "/life-architecture/assets/index--leb3gQZ.js",
  "/life-architecture/assets/index-BmmMk0cz.css",
  "/life-architecture/assets/index-qlrAbvMj.js",
  "/life-architecture/assets/web-CcVx3PfR.js",
  "/life-architecture/fonts/fonts.css",
  "/life-architecture/fonts/v17-rP2Yp2ywxg089UriI5-g4vlH9VoD8Cmcqbu0-K4.woff2",
  "/life-architecture/fonts/v17-rP2Yp2ywxg089UriI5-g4vlH9VoD8Cmcqbu6-K6h9Q.woff2",
  "/life-architecture/fonts/v22-V8mDoQDjQSkFtoMM3T6r8E7mPb54C-s0.woff2",
  "/life-architecture/fonts/v22-V8mDoQDjQSkFtoMM3T6r8E7mPb94C-s0.woff2",
  "/life-architecture/fonts/v22-V8mDoQDjQSkFtoMM3T6r8E7mPbF4Cw.woff2",
  "/life-architecture/fonts/v24-tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPx3cwhsk.woff2",
  "/life-architecture/fonts/v24-tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPx7cwhsk.woff2",
  "/life-architecture/fonts/v24-tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPxDcwg.woff2",
  "/life-architecture/fonts/v24-tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPxPcwhsk.woff2",
  "/life-architecture/fonts/v24-tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPxTcwhsk.woff2",
  "/life-architecture/fonts/v24-tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPx_cwhsk.woff2"
];
const CACHE_ONLY = [
  
];
const IGNORE = [
  new RegExp("^\\/life-architecture\\/(whist|breathe|focus|games|calories|ortho|chess)\\/", "")
];

self.addEventListener("install", (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      Promise.all(
        PRECACHE.map((url) =>
          cache.add(new Request(url, { cache: "reload" })).catch((err) => {
            console.warn("[sw] precache failed:", url, err);
          })
        )
      )
    )
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME && key !== DATA_CACHE)
          .map((key) => caches.delete(key))
      );
      await self.clients.claim();
      const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
      for (const client of clients) client.postMessage({ type: "sw-activated" });
    })()
  );
});

const isData = (request) => CACHE_ONLY.some((re) => re.test(request.url));

async function match(request, options) {
  const cache = await caches.open(isData(request) ? DATA_CACHE : CACHE_NAME);
  return cache.match(request, options);
}

async function put(request, response) {
  if (!response || !response.ok || response.type !== "basic") return;
  try {
    const cache = await caches.open(isData(request) ? DATA_CACHE : CACHE_NAME);
    await cache.put(request, response);
  } catch (err) {
    console.warn("[sw] cache put failed:", request.url, err);
  }
}

async function networkFirst(event) {
  const { request } = event;
  try {
    const response = await fetch(request);
    event.waitUntil(put(request, response.clone()));
    return response;
  } catch {
    const cached =
      (await match(request, { ignoreSearch: true })) || (await match(INDEX_URL));
    return cached || Response.error();
  }
}

async function cacheFirst(event) {
  const { request } = event;
  const cached = await match(request);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    event.waitUntil(put(request, response.clone()));
    return response;
  } catch {
    return Response.error();
  }
}

async function staleWhileRevalidate(event) {
  const { request } = event;
  const cached = await match(request);
  const network = fetch(request).then(
    (response) => {
      event.waitUntil(put(request, response.clone()));
      return response;
    },
    () => null
  );
  if (cached) {
    event.waitUntil(network);
    return cached;
  }
  return (await network) || Response.error();
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(SCOPE_PATH)) return;
  if (IGNORE.some((re) => re.test(url.pathname))) return;
  // Partial responses (206) cannot be cached; leave media range requests to the network.
  if (request.headers.has("range")) return;

  if (request.mode === "navigate") {
    event.respondWith(networkFirst(event));
  } else if (url.pathname.includes("/assets/") || CACHE_ONLY.some((re) => re.test(url.href))) {
    event.respondWith(cacheFirst(event));
  } else {
    event.respondWith(staleWhileRevalidate(event));
  }
});
