/* Generated by packages/shared/vite/swPlugin.js. Do not edit. */
const CACHE_NAME = "ortho-274c10cc";
const CACHE_PREFIX = "ortho-";
// Large cache-only files (engine nets, game databases) live in a cache that
// survives deploys; only the per-build cache is replaced on activate.
const DATA_CACHE = CACHE_PREFIX + "data";
const INDEX_URL = new URL("/life-architecture/ortho/index.html", self.location).href;
const SCOPE_PATH = new URL(self.registration.scope).pathname;
const PRECACHE = [
  "/life-architecture/ortho/",
  "/life-architecture/ortho/index.html",
  "/life-architecture/ortho/manifest.json",
  "/life-architecture/ortho/icon-192.png",
  "/life-architecture/ortho/icon-512.png",
  "/life-architecture/ortho/assets/_template-case-prep-IWNk4RSf.js",
  "/life-architecture/ortho/assets/_template-classification-eonMT-JM.js",
  "/life-architecture/ortho/assets/_template-technique-BD7fWZge.js",
  "/life-architecture/ortho/assets/ac-joint-reconstruction-CAH2xolz.js",
  "/life-architecture/ortho/assets/acdf-anterior-cervical-discectomy-fusion-BMvk2N4D.js",
  "/life-architecture/ortho/assets/acetabular-orif-approach-selection-87LxO-_X.js",
  "/life-architecture/ortho/assets/achilles-surgery-insertional-midportion-zadek-osteotomy-YIQcaQIA.js",
  "/life-architecture/ortho/assets/achilles-tendinopathy-debridement-fhl-augmentation-CAsCN_y2.js",
  "/life-architecture/ortho/assets/achilles-tendinopathy-insertional-midportion-haglund-classification-CZx36m9W.js",
  "/life-architecture/ortho/assets/achilles-tendon-rupture-repair-DmOsf3A3.js",
  "/life-architecture/ortho/assets/acl-reconstruction-lateral-extra-articular-tenodesis-KGvYzyAJ.js",
  "/life-architecture/ortho/assets/acute-tha-fix-and-replace-acetabular-fracture-Chq9JmAw.js",
  "/life-architecture/ortho/assets/adult-spinal-deformity-correction-osteotomy-ladder-YLYcmS7J.js",
  "/life-architecture/ortho/assets/ahlback-classification-knee-ZZKPYMHU.js",
  "/life-architecture/ortho/assets/allman-classification-clavicle-BOZt-dSk.js",
  "/life-architecture/ortho/assets/anatomic-total-shoulder-arthroplasty-jgBklvbM.js",
  "/life-architecture/ortho/assets/anderson-dalonzo-odontoid-classification-BPrtoLyc.js",
  "/life-architecture/ortho/assets/ankle-fracture-syndesmosis-orif-BFD3-4Z6.js",
  "/life-architecture/ortho/assets/ankle-hindfoot-midfoot-trauma-9dPbAcwn.js",
  "/life-architecture/ortho/assets/antegrade-im-nailing-femoral-shaft-93cbbglm.js",
  "/life-architecture/ortho/assets/anterior-odontoid-screw-fixation-xiFg2Yn_.js",
  "/life-architecture/ortho/assets/ao-ota-11-proximal-humerus-BVb6Hksz.js",
  "/life-architecture/ortho/assets/ao-ota-12-humeral-shaft-CdR1Zzs9.js",
  "/life-architecture/ortho/assets/ao-ota-13-distal-humerus-DzaqKSNl.js",
  "/life-architecture/ortho/assets/ao-ota-23-distal-radius-BgfExaok.js",
  "/life-architecture/ortho/assets/ao-ota-31-proximal-femur-Be5F28yu.js",
  "/life-architecture/ortho/assets/ao-ota-32-femoral-shaft-B57WZDOC.js",
  "/life-architecture/ortho/assets/ao-ota-33-distal-femur-BocjGSB2.js",
  "/life-architecture/ortho/assets/ao-ota-41-tibial-plateau-CBj7H7wb.js",
  "/life-architecture/ortho/assets/ao-ota-42-tibial-shaft-Cf0nWiK8.js",
  "/life-architecture/ortho/assets/ao-ota-43-pilon-T90UfGo-.js",
  "/life-architecture/ortho/assets/ao-spine-subaxial-cervical-injury-classification-DPDaQMg2.js",
  "/life-architecture/ortho/assets/ao-spine-thoracolumbar-injury-classification-BRiWKeum.js",
  "/life-architecture/ortho/assets/aori-classification-knee-defects-revision-tka-CLGcVwd7.js",
  "/life-architecture/ortho/assets/arco-2019-classification-osteonecrosis-femoral-head-DobVxAKA.js",
  "/life-architecture/ortho/assets/arthroscopic-bankart-repair-remplissage-BiT2yT96.js",
  "/life-architecture/ortho/assets/arthroscopic-reduction-fixation-tibial-spine-avulsion-V6qz5YfA.js",
  "/life-architecture/ortho/assets/arthroscopic-rotator-cuff-repair-Bdfe3W-u.js",
  "/life-architecture/ortho/assets/asa-physical-status-classification-perioperative-CPv4IQt2.js",
  "/life-architecture/ortho/assets/asbmr-atypical-femoral-fracture-criteria-CT3dprCm.js",
  "/life-architecture/ortho/assets/asia-impairment-scale-spinal-cord-injury-CHx_jvdV.js",
  "/life-architecture/ortho/assets/atypical-femoral-fracture-im-nailing-Duv82Lqc.js",
  "/life-architecture/ortho/assets/bado-monteggia-edV2rpJO.js",
  "/life-architecture/ortho/assets/bamic-classification-muscle-injury-LLykRHju.js",
  "/life-architecture/ortho/assets/barbotage-calcific-tendinopathy-etoowknm.js",
  "/life-architecture/ortho/assets/biceps-tenodesis-Cs15qyhS.js",
  "/life-architecture/ortho/assets/bilsky-classification-epidural-spinal-cord-compression-KyWnNEpT.js",
  "/life-architecture/ortho/assets/blazina-classification-patellar-tendinopathy-IJy-xO6I.js",
  "/life-architecture/ortho/assets/blount-disease-guided-growth-osteotomy-CJY9A1xG.js",
  "/life-architecture/ortho/assets/bone-marrow-aspirate-concentrate-harvest-injection-CWTRCyH_.js",
  "/life-architecture/ortho/assets/bone-soft-tissue-tumors-B04jBqUb.js",
  "/life-architecture/ortho/assets/bone-transport-distraction-osteogenesis-B6cFquCA.js",
  "/life-architecture/ortho/assets/bony-bankart-fixation-y5KIfIYj.js",
  "/life-architecture/ortho/assets/both-bone-forearm-fracture-fixation-3ZP9o6zd.js",
  "/life-architecture/ortho/assets/brodsky-classification-charcot-foot-CQa3c4Zw.js",
  "/life-architecture/ortho/assets/budapest-criteria-crps-BAGvCJJi.js",
  "/life-architecture/ortho/assets/calcaneus-fracture-orif-vhePozAU.js",
  "/life-architecture/ortho/assets/campanacci-classification-giant-cell-tumor-Djk2xfO-.js",
  "/life-architecture/ortho/assets/caprini-score-perioperative-vte-risk-s6tkL7Rf.js",
  "/life-architecture/ortho/assets/carpal-tunnel-release-open-endoscopic-walant-B6sJYkFo.js",
  "/life-architecture/ortho/assets/cartilage-restoration-ladder-knee-BBsaIVlV.js",
  "/life-architecture/ortho/assets/caton-deschamps-index-CnfDOq6o.js",
  "/life-architecture/ortho/assets/cavovarus-foot-reconstruction-BQnUBx93.js",
  "/life-architecture/ortho/assets/cementation-technique-bcis-prevention-nfpSnT7T.js",
  "/life-architecture/ortho/assets/cephalomedullary-nailing-intertrochanteric-C5dTPN4T.js",
  "/life-architecture/ortho/assets/cephalomedullary-nailing-subtrochanteric-Ckruh47M.js",
  "/life-architecture/ortho/assets/cervical-disc-arthroplasty-hGY5HDBy.js",
  "/life-architecture/ortho/assets/cervical-epidural-steroid-injection-QTKUlOzq.js",
  "/life-architecture/ortho/assets/cervical-spine-degenerative-BVH_YYPc.js",
  "/life-architecture/ortho/assets/cfa-classification-chronic-ankle-instability-BvaXD5MU.js",
  "/life-architecture/ortho/assets/charcot-foot-reconstruction-superconstruct-B8IvbSE7.js",
  "/life-architecture/ortho/assets/cheilectomy-moberg-osteotomy-hallux-rigidus-B16Jdrgl.js",
  "/life-architecture/ortho/assets/chronic-osteomyelitis-debridement-dead-space-management-BYtaqoGE.js",
  "/life-architecture/ortho/assets/cierny-mader-classification-osteomyelitis-CiPbs2YV.js",
  "/life-architecture/ortho/assets/clavicle-orif-plating-DFxb5WU6.js",
  "/life-architecture/ortho/assets/clavien-dindo-classification-surgical-complications-DJ7t0IdX.js",
  "/life-architecture/ortho/assets/closed-reduction-casting-distal-radius-oO_mzmJv.js",
  "/life-architecture/ortho/assets/cobb-angle-thresholds-scoliosis-liiA_f4H.js",
  "/life-architecture/ortho/assets/cofield-classification-rotator-cuff-tear-size-sR_kMkvY.js",
  "/life-architecture/ortho/assets/coleman-block-test-cavovarus-foot-CTxXbYeo.js",
  "/life-architecture/ortho/assets/constraint-ladder-revision-tka-DWpY2dha.js",
  "/life-architecture/ortho/assets/content-fulltext-BUQc4aAw.js",
  "/life-architecture/ortho/assets/core-decompression-biologic-augmentation-osteonecrosis-DH7U9YXo.js",
  "/life-architecture/ortho/assets/corrective-osteotomy-malunion-lBoroFcU.js",
  "/life-architecture/ortho/assets/corticosteroid-injection-intra-articular-soft-tissue-DB9r_qjR.js",
  "/life-architecture/ortho/assets/coughlin-classification-bunionette-D3AXGbNn.js",
  "/life-architecture/ortho/assets/coughlin-nery-plantar-plate-tear-classification-BYbw3lJc.js",
  "/life-architecture/ortho/assets/coughlin-shurnas-classification-hallux-rigidus-CA57fpqk.js",
  "/life-architecture/ortho/assets/coxa-vara-valgus-osteotomy-m5NzAqU7.js",
  "/life-architecture/ortho/assets/cpak-classification-knee-Uyg99LI3.js",
  "/life-architecture/ortho/assets/crowe-classification-hip-dysplasia-Cn3JjT3O.js",
  "/life-architecture/ortho/assets/crpp-pediatric-supracondylar-humerus-fracture-Cg6IZk67.js",
  "/life-architecture/ortho/assets/cubital-tunnel-decompression-transposition-zZ2zY3zU.js",
  "/life-architecture/ortho/assets/dair-debridement-antibiotics-implant-retention-y4e1wgs0.js",
  "/life-architecture/ortho/assets/damage-control-external-fixation-femur-6YfE4jmL.js",
  "/life-architecture/ortho/assets/damage-control-orthopaedics-polytrauma-staging-hJsCWqeR.js",
  "/life-architecture/ortho/assets/ddh-closed-reduction-spica-casting-CEyw6QWU.js",
  "/life-architecture/ortho/assets/ddh-open-reduction-osteotomy-CANdte8e.js",
  "/life-architecture/ortho/assets/debridement-instrumented-fusion-spondylodiscitis-CL2Sp6_l.js",
  "/life-architecture/ortho/assets/dejour-classification-trochlear-dysplasia-B7F74WbQ.js",
  "/life-architecture/ortho/assets/denis-classification-sacral-fractures-DhrU8Q7A.js",
  "/life-architecture/ortho/assets/diabetic-foot-ulcer-debridement-limb-salvage-Bv_bsS16.js",
  "/life-architecture/ortho/assets/diagnostic-joint-aspiration-Cnabqfvo.js",
  "/life-architecture/ortho/assets/diamond-concept-nonunion-fixation-Dp6GnwLp.js",
  "/life-architecture/ortho/assets/dimeglio-classification-clubfoot-CqrFUq9u.js",
  "/life-architecture/ortho/assets/discoid-meniscus-saucerization-repair-iUmCYGsl.js",
  "/life-architecture/ortho/assets/distal-biceps-tendon-repair-Cw95_c20.js",
  "/life-architecture/ortho/assets/distal-femoral-replacement-CkowORjy.js",
  "/life-architecture/ortho/assets/distal-humerus-fracture-fixation-orif-tea-BGBcPdsc.js",
  "/life-architecture/ortho/assets/distal-radius-fractures-CzYBI5Op.js",
  "/life-architecture/ortho/assets/donaldson-classification-bone-cement-implantation-syndrome-B0xYkhYx.js",
  "/life-architecture/ortho/assets/dorr-classification-femoral-bone-D7kv_J_O.js",
  "/life-architecture/ortho/assets/druj-stabilization-fixation-BlK0Y9SO.js",
  "/life-architecture/ortho/assets/eaton-littler-classification-thumb-cmc-6z33WOsI.js",
  "/life-architecture/ortho/assets/ebjis-classification-pji-BHtYuYCp.js",
  "/life-architecture/ortho/assets/ecrb-flexor-pronator-debridement-epicondylitis-DlJlxyYg.js",
  "/life-architecture/ortho/assets/eichenholtz-classification-charcot-foot-_jE-2X_R.js",
  "/life-architecture/ortho/assets/elbow-debridement-outerbridge-kashiwagi-CHGRCISO.js",
  "/life-architecture/ortho/assets/elbow-dislocation-stability-classification-B-LPIWZV.js",
  "/life-architecture/ortho/assets/elbow-forearm-fractures-tELVR4uP.js",
  "/life-architecture/ortho/assets/ellman-classification-partial-thickness-rotator-cuff-tears-DTbj5GQG.js",
  "/life-architecture/ortho/assets/emergency-decompression-cauda-equina-syndrome-DBpAf2lD.js",
  "/life-architecture/ortho/assets/en-bloc-resection-sacrectomy-primary-spine-tumor-Cp8i_CH_.js",
  "/life-architecture/ortho/assets/enneking-msts-staging-bone-soft-tissue-tumors-bdwi101k.js",
  "/life-architecture/ortho/assets/enneking-staging-primary-spine-tumors-Dy_cYbFK.js",
  "/life-architecture/ortho/assets/eras-pathway-arthroplasty-trauma-BPx22qjK.js",
  "/life-architecture/ortho/assets/esin-both-bone-forearm-fracture-pediatric-BDE_I2du.js",
  "/life-architecture/ortho/assets/essex-lopresti-operative-management-CqVJENMJ.js",
  "/life-architecture/ortho/assets/evans-jensen-classification-intertrochanteric-DeQFi9ME.js",
  "/life-architecture/ortho/assets/exchange-nailing-femoral-shaft-nonunion-BVuFtTIp.js",
  "/life-architecture/ortho/assets/extended-curettage-adjuvant-benign-bone-tumors-DXL4dn9Y.js",
  "/life-architecture/ortho/assets/extensor-tendon-zones-hand-DxScqWxp.js",
  "/life-architecture/ortho/assets/fanelli-classification-posterolateral-corner-XxHoqkIV.js",
  "/life-architecture/ortho/assets/favard-classification-glenoid-erosion-cuff-tear-arthropathy-CZswk_Bh.js",
  "/life-architecture/ortho/assets/femoral-derotational-osteotomy-anteversion-uU8j8b-1.js",
  "/life-architecture/ortho/assets/femoral-shaft-distal-femur-fractures-Rwkud_I5.js",
  "/life-architecture/ortho/assets/fernandez-classification-distal-radius-C62GN0hS.js",
  "/life-architecture/ortho/assets/ffp-rommens-classification-fragility-pelvis-BAA2tFNl.js",
  "/life-architecture/ortho/assets/ficat-arlet-classification-osteonecrosis-BYpc-XLH.js",
  "/life-architecture/ortho/assets/first-mtp-arthrodesis-hallux-rigidus-mm4VLS0_.js",
  "/life-architecture/ortho/assets/flexible-intramedullary-nailing-pediatric-femur-fracture-DCFcOf-j.js",
  "/life-architecture/ortho/assets/flexor-tendon-repair-early-active-motion-CGxsItg0.js",
  "/life-architecture/ortho/assets/forefoot-disorders-CpWDz5sx.js",
  "/life-architecture/ortho/assets/four-compartment-fasciotomy-leg-BzAAPf7V.js",
  "/life-architecture/ortho/assets/fracture-related-infection-dair-staged-exchange-DfBpDuJt.js",
  "/life-architecture/ortho/assets/frax-dexa-t-score-osteoporosis-Ds7vUpba.js",
  "/life-architecture/ortho/assets/fri-consensus-definition-confirmatory-criteria-D_50R2ux.js",
  "/life-architecture/ortho/assets/frozen-shoulder-mua-arthroscopic-capsular-release-CZFSlOxw.js",
  "/life-architecture/ortho/assets/frykman-classification-distal-radius-B4_goxr9.js",
  "/life-architecture/ortho/assets/garcia-elias-staging-scapholunate-instability-ChqBsgmf.js",
  "/life-architecture/ortho/assets/garden-classification-femoral-neck-DKLOo9rj.js",
  "/life-architecture/ortho/assets/gartland-classification-supracondylar-humerus-fracture-BdjeMy5q.js",
  "/life-architecture/ortho/assets/gartner-classification-calcific-tendinopathy-shoulder-CyHtcTpV.js",
  "/life-architecture/ortho/assets/gauthier-osteotomy-freiberg-disease-tjqvzK1I.js",
  "/life-architecture/ortho/assets/genicular-nerve-block-radiofrequency-ablation-CKWPoCce.js",
  "/life-architecture/ortho/assets/glenoid-track-on-off-track-shoulder-instability-C_gneKR1.js",
  "/life-architecture/ortho/assets/gluteus-medius-minimus-repair-gtps-CGYxRjtp.js",
  "/life-architecture/ortho/assets/gmfcs-cerebral-palsy-CByRfeeo.js",
  "/life-architecture/ortho/assets/goutallier-classification-fatty-infiltration-rotator-cuff-vm6cB0K6.js",
  "/life-architecture/ortho/assets/graf-classification-hip-ultrasound-ddh-Bw0lyBEe.js",
  "/life-architecture/ortho/assets/green-classification-trigger-finger-E2KOKdhj.js",
  "/life-architecture/ortho/assets/guided-growth-epiphysiodesis-limb-length-discrepancy-QMfycOEn.js",
  "/life-architecture/ortho/assets/gustilo-anderson-classification-infection-risk-context-DzMZC0ij.js",
  "/life-architecture/ortho/assets/gustilo-anderson-open-fractures-COSLAof7.js",
  "/life-architecture/ortho/assets/hagl-repair-vNtWcO2c.js",
  "/life-architecture/ortho/assets/hallux-valgus-osteotomy-chevron-scarf-akin-mis-_bwFMyhg.js",
  "/life-architecture/ortho/assets/hallux-valgus-severity-hva-ima-classification-C4ObUUX2.js",
  "/life-architecture/ortho/assets/hamada-classification-cuff-tear-arthropathy-C3zg_cQC.js",
  "/life-architecture/ortho/assets/hammer-claw-mallet-toe-classification-X_tHVBKH.js",
  "/life-architecture/ortho/assets/hand-infection-surgical-drainage-oGCEGGKu.js",
  "/life-architecture/ortho/assets/hand-wrist-conditions-AcXgz9Dd.js",
  "/life-architecture/ortho/assets/hangman-fracture-fixation-BsqzpMuk.js",
  "/life-architecture/ortho/assets/hartofilakidis-classification-hip-dysplasia-5wc20Tqg.js",
  "/life-architecture/ortho/assets/hawkins-classification-talar-neck-fracture-D_EUdNKj.js",
  "/life-architecture/ortho/assets/hepple-berndt-harty-classification-osteochondral-lesion-talus-aXhzhPTF.js",
  "/life-architecture/ortho/assets/herbert-fisher-classification-scaphoid-fracture-EqrjWCWB.js",
  "/life-architecture/ortho/assets/herring-lateral-pillar-classification-perthes-Dq7nLjUV.js",
  "/life-architecture/ortho/assets/high-tibial-osteotomy-BpBiYIza.js",
  "/life-architecture/ortho/assets/hindfoot-ankle-disorders-BrWIH439.js",
  "/life-architecture/ortho/assets/hip-arthroplasty-femoral-neck-fracture-p_nimv0o.js",
  "/life-architecture/ortho/assets/hip-arthroscopy-fai-labral-pathology-lcWkq2Gz.js",
  "/life-architecture/ortho/assets/hip-osteoarthritis-tha-DsdJskMh.js",
  "/life-architecture/ortho/assets/how-to-add-content--qG1RMh7.js",
  "/life-architecture/ortho/assets/humeral-shaft-intramedullary-nailing-C7ZthaeD.js",
  "/life-architecture/ortho/assets/humeral-shaft-orif-plating-CjYPd51S.js",
  "/life-architecture/ortho/assets/icm-msis-classification-pji-CwH7kohq.js",
  "/life-architecture/ortho/assets/icrs-classification-knee-cartilage-DDLR7dpl.js",
  "/life-architecture/ortho/assets/icrs-ocd-staging-knee-mDWH_n9a.js",
  "/life-architecture/ortho/assets/ideberg-classification-glenoid-JwqpA9mc.js",
  "/life-architecture/ortho/assets/idsa-iwgdf-classification-diabetic-foot-infection-D1r1Mdfs.js",
  "/life-architecture/ortho/assets/ihdi-classification-developmental-dysplasia-hip-CjZhbiwT.js",
  "/life-architecture/ortho/assets/index-BQrqbRDc.css",
  "/life-architecture/ortho/assets/index-C-sML0M8.js",
  "/life-architecture/ortho/assets/index-CNKxlSs8.js",
  "/life-architecture/ortho/assets/inferior-capsular-shift-plication-mdi-B6bzvD51.js",
  "/life-architecture/ortho/assets/injections-orthobiologics-BZ7yoBp5.js",
  "/life-architecture/ortho/assets/interposition-arthroplasty-elbow-BuwgOLNZ.js",
  "/life-architecture/ortho/assets/intramedullary-nailing-metastatic-bone-disease--QcPhhgi.js",
  "/life-architecture/ortho/assets/isis-score-shoulder-instability-Dn4D483f.js",
  "/life-architecture/ortho/assets/isthmic-spondylolisthesis-fusion-pars-repair-BQqfRuq1.js",
  "/life-architecture/ortho/assets/jefferson-fracture-c1-ring-stability-vPpA1cbW.js",
  "/life-architecture/ortho/assets/judet-classification-radial-neck-fracture-DPWdA_GP.js",
  "/life-architecture/ortho/assets/judet-letournel-acetabular-fractures-CvhI_-vn.js",
  "/life-architecture/ortho/assets/juvenile-ocd-knee-drilling-fixation-cartilage-restoration-BYjokpHc.js",
  "/life-architecture/ortho/assets/k-line-opll-BI-Rcof_.js",
  "/life-architecture/ortho/assets/kanavel-signs-flexor-sheath-infection-CIB_4l36.js",
  "/life-architecture/ortho/assets/kellgren-lawrence-hip-Ur4pMJEw.js",
  "/life-architecture/ortho/assets/kellgren-lawrence-injection-response-CgSILb5Z.js",
  "/life-architecture/ortho/assets/kellgren-lawrence-knee-D7rir_cO.js",
  "/life-architecture/ortho/assets/kienbock-disease-joint-leveling-revascularization-Ymux7ryJ.js",
  "/life-architecture/ortho/assets/knee-ligament-injuries-Cv6g_GAm.js",
  "/life-architecture/ortho/assets/knee-osteoarthritis-tka-BVytmSmO.js",
  "/life-architecture/ortho/assets/kocher-criteria-septic-arthritis-pediatric-hip-dR1KdgC9.js",
  "/life-architecture/ortho/assets/kocher-criteria-septic-arthritis-transient-synovitis-CwkjgNSe.js",
  "/life-architecture/ortho/assets/lafosse-classification-subscapularis-tears-KSYO5L42.js",
  "/life-architecture/ortho/assets/laminectomy-instrumented-fusion-cervical-myelopathy-B3-x_bu2.js",
  "/life-architecture/ortho/assets/laminoplasty-cervical-myelopathy-opll-CKxAD3mp.js",
  "/life-architecture/ortho/assets/langenskiold-classification-blount-disease-Cu3Vnhqk.js",
  "/life-architecture/ortho/assets/lapidus-procedure-1st-tmt-arthrodesis-hallux-valgus-C-PQhOLO.js",
  "/life-architecture/ortho/assets/laprade-classification-meniscal-root-tears-Bl974D9T.js",
  "/life-architecture/ortho/assets/latarjet-procedure-DeAe136H.js",
  "/life-architecture/ortho/assets/lateral-condyle-fracture-fixation-pediatric-Cd3ywQV8.js",
  "/life-architecture/ortho/assets/lauge-hansen-classification-ankle-fracture-DuMBdXUH.js",
  "/life-architecture/ortho/assets/lee-classification-lumbar-disc-herniation-zones-DhydPaRF.js",
  "/life-architecture/ortho/assets/lenke-classification-adolescent-idiopathic-scoliosis-Dh0Tozin.js",
  "/life-architecture/ortho/assets/levine-edwards-hangman-classification-CEW4c5ew.js",
  "/life-architecture/ortho/assets/lewis-rorabeck-classification-periprosthetic-tka-fracture-C7rHsaIr.js",
  "/life-architecture/ortho/assets/lichtman-classification-kienbock-disease-CXoQjbGz.js",
  "/life-architecture/ortho/assets/limb-salvage-resection-endoprosthetic-reconstruction-bone-sarcoma-BIkVUTRh.js",
  "/life-architecture/ortho/assets/lisfranc-injury-fixation-oDCJrPJF.js",
  "/life-architecture/ortho/assets/locked-distal-femoral-plating-liss-CNfXMuCT.js",
  "/life-architecture/ortho/assets/loder-classification-scfe-stability-BmbyHu0W.js",
  "/life-architecture/ortho/assets/lodwick-madewell-classification-bone-lesions-BlsM4GYN.js",
  "/life-architecture/ortho/assets/lower-trapezius-tendon-transfer-B3BIxauR.js",
  "/life-architecture/ortho/assets/lrinec-score-necrotizing-fasciitis-BeVZ0K9O.js",
  "/life-architecture/ortho/assets/lumbar-decompression-fusion-degenerative-spondylolisthesis-C_ZaT7xF.js",
  "/life-architecture/ortho/assets/lumbar-decompression-spinal-stenosis-CRUiQjmB.js",
  "/life-architecture/ortho/assets/lumbar-degenerative-spine-32UsGpfY.js",
  "/life-architecture/ortho/assets/lumbar-microdiscectomy-endoscopic-discectomy-CiHxW1EV.js",
  "/life-architecture/ortho/assets/luo-three-column-classification-tibial-plateau-BQL8WTKL.js",
  "/life-architecture/ortho/assets/manipulation-under-anesthesia-stiff-tka-7AfXn1xD.js",
  "/life-architecture/ortho/assets/mason-molloy-classification-posterior-malleolus-fracture-B9XOXLlG.js",
  "/life-architecture/ortho/assets/mason-radial-head-fracture-DnNVF3En.js",
  "/life-architecture/ortho/assets/masquelet-induced-membrane-technique-Dh8yp3-4.js",
  "/life-architecture/ortho/assets/mayfield-classification-perilunate-instability-DsO8nc7H.js",
  "/life-architecture/ortho/assets/mayo-classification-scaphoid-fracture-location-DpmXBtAM.js",
  "/life-architecture/ortho/assets/mayo-olecranon-fracture-CEo6p3EC.js",
  "/life-architecture/ortho/assets/mcgowan-classification-cubital-tunnel-syndrome-MYYFuPGE.js",
  "/life-architecture/ortho/assets/mcl-grading-classification-knee-ERgnB3jy.js",
  "/life-architecture/ortho/assets/mcl-posteromedial-corner-repair-reconstruction-MOsHenVW.js",
  "/life-architecture/ortho/assets/mcpherson-host-grading-classification-pji-BQoHlXyU.js",
  "/life-architecture/ortho/assets/medial-epicondyle-fracture-fixation-pediatric-CjVNzmwc.js",
  "/life-architecture/ortho/assets/melone-classification-distal-radius-AVCsYV7Y.js",
  "/life-architecture/ortho/assets/meniscal-root-repair-transtibial-pullout-C0BQN-W6.js",
  "/life-architecture/ortho/assets/meniscus-cartilage-lesions-DhBCZV1x.js",
  "/life-architecture/ortho/assets/meniscus-repair-peripheral-tears-CJbLCCtF.js",
  "/life-architecture/ortho/assets/meniscus-tear-morphology-DDK-Ene9.js",
  "/life-architecture/ortho/assets/metacarpal-phalangeal-fracture-fixation-C2zSwkz_.js",
  "/life-architecture/ortho/assets/metaizeau-technique-radial-neck-fracture-reduction-BY5rOA8K.js",
  "/life-architecture/ortho/assets/meyerding-classification-lumbar-spondylolisthesis-DvIZuFnN.js",
  "/life-architecture/ortho/assets/meyers-mckeever-classification-tibial-spine-avulsion-B0yiDEXN.js",
  "/life-architecture/ortho/assets/milch-jakob-weiss-classification-lateral-condyle-fracture-Bq49yAGL.js",
  "/life-architecture/ortho/assets/mirels-score-pathologic-fracture-risk-DQicQLjH.js",
  "/life-architecture/ortho/assets/mjoa-severity-score-cervical-myelopathy-DKH64fIT.js",
  "/life-architecture/ortho/assets/modic-classification-vertebral-endplate-changes-BXmE7GCx.js",
  "/life-architecture/ortho/assets/modified-brostrom-gould-ankle-ligament-reconstruction-BDM8gZ7c.js",
  "/life-architecture/ortho/assets/monteggia-galeazzi-fixation-BbOQbMkA.js",
  "/life-architecture/ortho/assets/morton-neuroma-neurectomy-Sx-BVzCb.js",
  "/life-architecture/ortho/assets/mpfl-reconstruction-BCUKXV_w.js",
  "/life-architecture/ortho/assets/msk-infection-metabolic-bone-BvA9I0H1.js",
  "/life-architecture/ortho/assets/multiligament-knee-reconstruction-staged-management-DE3wDbQG.js",
  "/life-architecture/ortho/assets/myerson-classification-lisfranc-injury-C8_3ehA2.js",
  "/life-architecture/ortho/assets/nail-plate-combined-construct-distal-femur-Do6tI1Zh.js",
  "/life-architecture/ortho/assets/native-septic-arthritis-washout-Bo-iU56r.js",
  "/life-architecture/ortho/assets/navicular-cuboid-fracture-fixation-CAYUG6Qh.js",
  "/life-architecture/ortho/assets/necrotizing-fasciitis-radical-debridement-CFvwEV3T.js",
  "/life-architecture/ortho/assets/neer-classification-distal-clavicle-C_xVce08.js",
  "/life-architecture/ortho/assets/neer-classification-proximal-humerus-BRYSIfBk.js",
  "/life-architecture/ortho/assets/nonunion-types-classification-DbysGLw-.js",
  "/life-architecture/ortho/assets/nunley-vertullo-classification-lisfranc-injury-5vVbZX7r.js",
  "/life-architecture/ortho/assets/nurick-grade-cervical-myelopathy-8ozE6CH_.js",
  "/life-architecture/ortho/assets/ocd-fixation-drilling-adult-knee-kP-7jNfM.js",
  "/life-architecture/ortho/assets/odriscoll-coronoid-fracture-CNCMBXkx.js",
  "/life-architecture/ortho/assets/olecranon-fracture-fixation-Dm_EdCZV.js",
  "/life-architecture/ortho/assets/olt-treatment-ladder-bone-marrow-stimulation-restorative-DjgJ9rYB.js",
  "/life-architecture/ortho/assets/one-stage-exchange-arthroplasty-pji-C3fEexLD.js",
  "/life-architecture/ortho/assets/open-fracture-debridement-fix-and-flap-3X1QKEOM.js",
  "/life-architecture/ortho/assets/open-fractures-polytrauma-principles-Cako8VML.js",
  "/life-architecture/ortho/assets/opll-morphologic-classification-CPIaZk_D.js",
  "/life-architecture/ortho/assets/osteonecrosis-hip-preservation-DPQz9sQ5.js",
  "/life-architecture/ortho/assets/ota-open-fracture-classification-f1jeI0Kw.js",
  "/life-architecture/ortho/assets/outerbridge-classification-knee-cartilage-DZ9J0bBJ.js",
  "/life-architecture/ortho/assets/palmer-classification-tfcc-C3dA3Ws_.js",
  "/life-architecture/ortho/assets/paprosky-classification-acetabular-defects-DmPyK1SR.js",
  "/life-architecture/ortho/assets/paprosky-classification-acetabular-defects-revision-arthroplasty-D0BOSqOi.js",
  "/life-architecture/ortho/assets/paprosky-classification-femoral-defects-revision-arthroplasty-BuAQefzD.js",
  "/life-architecture/ortho/assets/partial-sesamoidectomy-sesamoid-pathology-CBiRtxpQ.js",
  "/life-architecture/ortho/assets/patellar-tendon-repair-Dg0mDqhe.js",
  "/life-architecture/ortho/assets/patellofemoral-arthroplasty-CAmJPRMW.js",
  "/life-architecture/ortho/assets/patellofemoral-extensor-mechanism-DWsamUY9.js",
  "/life-architecture/ortho/assets/patte-classification-rotator-cuff-retraction-bLoTA62g.js",
  "/life-architecture/ortho/assets/pauwels-classification-femoral-neck-D8VMGkoQ.js",
  "/life-architecture/ortho/assets/pcfd-consensus-classification-flatfoot-C-G5lTkp.js",
  "/life-architecture/ortho/assets/pcfd-flatfoot-reconstruction-ladder-CMOqI8zE.js",
  "/life-architecture/ortho/assets/pcl-grading-posterior-tibial-translation-D6l1aG7S.js",
  "/life-architecture/ortho/assets/pcl-reconstruction-Cu0tF2Lg.js",
  "/life-architecture/ortho/assets/pectoralis-major-repair-gERRe8FR.js",
  "/life-architecture/ortho/assets/pediatric-conditions-CfBrXNdL.js",
  "/life-architecture/ortho/assets/pediatric-hip-disorders-DUe1kAmW.js",
  "/life-architecture/ortho/assets/pediatric-trauma-Bt2cWosU.js",
  "/life-architecture/ortho/assets/pelvic-acetabular-fractures-De8uDBRQ.js",
  "/life-architecture/ortho/assets/pelvic-ring-definitive-fixation-percutaneous-screws-t-y-6DZO.js",
  "/life-architecture/ortho/assets/percutaneous-epiphyseal-screw-fixation-transitional-ankle-fracture-BTsADSVd.js",
  "/life-architecture/ortho/assets/percutaneous-kwire-fixation-distal-radius-OGy9eNzD.js",
  "/life-architecture/ortho/assets/percutaneous-screw-fixation-femoral-neck-BoCM0oT3.js",
  "/life-architecture/ortho/assets/percutaneous-screw-fixation-scaphoid-fracture-DQh0j_7Q.js",
  "/life-architecture/ortho/assets/percutaneous-vertebral-augmentation-vertebroplasty-kyphoplasty-BaaUczAG.js",
  "/life-architecture/ortho/assets/periacetabular-osteotomy-pao-CVqATpl2.js",
  "/life-architecture/ortho/assets/perilunate-dislocation-reduction-repair-BH8Xy1Cy.js",
  "/life-architecture/ortho/assets/perioperative-care-principles-B47tJZ8V.js",
  "/life-architecture/ortho/assets/periprosthetic-femur-fracture-orif-vancouver-a-b1-c-CTFjqYkB.js",
  "/life-architecture/ortho/assets/periprosthetic-femur-fracture-revision-arthroplasty-vancouver-b2-b3-CR5sqFV-.js",
  "/life-architecture/ortho/assets/periprosthetic-fractures-revision-arthroplasty-Bv65t1oN.js",
  "/life-architecture/ortho/assets/periprosthetic-joint-infection-C1y_RUu4.js",
  "/life-architecture/ortho/assets/periprosthetic-tka-fracture-fixation-revision-BK6z6J2x.js",
  "/life-architecture/ortho/assets/peroneal-tendon-repair-reconstruction-CmsW4Ryb.js",
  "/life-architecture/ortho/assets/perthes-containment-surgery-WbL70_DO.js",
  "/life-architecture/ortho/assets/pfirrmann-classification-lumbar-disc-degeneration-BSlEuZkV.js",
  "/life-architecture/ortho/assets/pipkin-classification-femoral-head-BPLgBiGe.js",
  "/life-architecture/ortho/assets/pirani-score-clubfoot-Bfporycs.js",
  "/life-architecture/ortho/assets/platelet-rich-plasma-injection-CiPZUMI2.js",
  "/life-architecture/ortho/assets/plc-lcl-repair-reconstruction-BVl1saBb.js",
  "/life-architecture/ortho/assets/ponseti-method-clubfoot-casting-tenotomy-bracing-DZuVZrrN.js",
  "/life-architecture/ortho/assets/posterior-c1-c2-fusion-goel-harms-C3WKdiOQ.js",
  "/life-architecture/ortho/assets/posterior-cervical-foraminotomy-DiaTHk-h.js",
  "/life-architecture/ortho/assets/posterior-labral-repair-shoulder--L850tuf.js",
  "/life-architecture/ortho/assets/posterior-malleolus-fixation-mason-molloy-C_fITPzB.js",
  "/life-architecture/ortho/assets/posterior-spinal-fusion-pedicle-screw-ais-CuLannQA.js",
  "/life-architecture/ortho/assets/preperitoneal-pelvic-packing-hemorrhage-control-DoNbT8Qt.js",
  "/life-architecture/ortho/assets/progressive-tendon-loading-patellar-tendinopathy-B6cgPTnd.js",
  "/life-architecture/ortho/assets/prolotherapy-injection-CYq-OzEt.js",
  "/life-architecture/ortho/assets/proximal-femur-fractures-HKY-IbHv.js",
  "/life-architecture/ortho/assets/proximal-hamstring-avulsion-repair-DLlQhLzl.js",
  "/life-architecture/ortho/assets/proximal-humerus-intramedullary-nailing-B46S-sVI.js",
  "/life-architecture/ortho/assets/proximal-humerus-orif-locking-plate-C1IoIdxj.js",
  "/life-architecture/ortho/assets/prp-preparation-classification-lr-vs-lp-DzmkyC5N.js",
  "/life-architecture/ortho/assets/puranen-orava-classification-hamstring-strain-CPJmss37.js",
  "/life-architecture/ortho/assets/quadriceps-tendon-repair-B8W3i96H.js",
  "/life-architecture/ortho/assets/radial-head-fracture-orif-and-arthroplasty-Ecm16AwE.js",
  "/life-architecture/ortho/assets/radiofrequency-ablation-osteoid-osteoma-BSd4j9w1.js",
  "/life-architecture/ortho/assets/ramp-lesion-repair-BXPr-uva.js",
  "/life-architecture/ortho/assets/retrograde-im-nailing-distal-femur-BYwXUYzy.js",
  "/life-architecture/ortho/assets/reverse-total-shoulder-arthroplasty-B39xESkk.js",
  "/life-architecture/ortho/assets/revision-tha-recurrent-instability-Dz-W5WEs.js",
  "/life-architecture/ortho/assets/risser-classification-scoliosis-skeletal-maturity-DjKVe0Xv.js",
  "/life-architecture/ortho/assets/robinson-classification-clavicle-CZ6TN4lg.js",
  "/life-architecture/ortho/assets/rockwood-classification-ac-joint-OdEFtNdr.js",
  "/life-architecture/ortho/assets/rotator-cuff-biceps-pathology-Jt8D6ZDE.js",
  "/life-architecture/ortho/assets/ruedi-allgower-classification-pilon-DNkzOWEi.js",
  "/life-architecture/ortho/assets/russe-classification-scaphoid-fracture-orientation-CwQG60bN.js",
  "/life-architecture/ortho/assets/salenius-vankka-curve-physiologic-tibiofemoral-angle-5TtpG3Cd.js",
  "/life-architecture/ortho/assets/salter-harris-classification-physeal-fractures-DmE2sQEl.js",
  "/life-architecture/ortho/assets/samilson-prieto-classification-glenohumeral-oa-C-pGv1Nd.js",
  "/life-architecture/ortho/assets/samilson-prieto-classification-post-instability-arthropathy-uK9K1K2x.js",
  "/life-architecture/ortho/assets/sanders-classification-calcaneus-fracture-CSsoL9G5.js",
  "/life-architecture/ortho/assets/sc-joint-reduction-DMGI4gCf.js",
  "/life-architecture/ortho/assets/scaphoid-carpal-instability-D7lXsxCK.js",
  "/life-architecture/ortho/assets/scaphoid-nonunion-bone-grafting-Bjwdtw3E.js",
  "/life-architecture/ortho/assets/scapholunate-ligament-repair-reconstruction-C1JIynf3.js",
  "/life-architecture/ortho/assets/scapular-glenoid-orif-DulKvQYO.js",
  "/life-architecture/ortho/assets/scfe-in-situ-pinning-gNQxn0cw.js",
  "/life-architecture/ortho/assets/scfe-modified-dunn-procedure-C-269X5d.js",
  "/life-architecture/ortho/assets/schatzker-classification-tibial-plateau-C3PjoRIl.js",
  "/life-architecture/ortho/assets/schenck-classification-knee-dislocation-Duo1Zege.js",
  "/life-architecture/ortho/assets/schizas-classification-lumbar-spinal-stenosis-BbPCvKj9.js",
  "/life-architecture/ortho/assets/segond-fracture-reverse-segond-knee-h5BlpoUL.js",
  "/life-architecture/ortho/assets/seinsheimer-classification-subtrochanteric-BxwWFNRv.js",
  "/life-architecture/ortho/assets/separation-surgery-sbrt-metastatic-spinal-cord-compression-B1VwSki1.js",
  "/life-architecture/ortho/assets/sesamoid-pathology-diagnostic-categories-D9V0542m.js",
  "/life-architecture/ortho/assets/shoulder-arthroplasty-proximal-humerus-fracture-Ccm3wZAU.js",
  "/life-architecture/ortho/assets/shoulder-elbow-arthritis-arthroplasty-Bu81MB5P.js",
  "/life-architecture/ortho/assets/shoulder-girdle-humerus-fractures-DNf763ik.js",
  "/life-architecture/ortho/assets/shoulder-instability-CdNeOkm2.js",
  "/life-architecture/ortho/assets/sins-spinal-instability-neoplastic-score-749Uux8L.js",
  "/life-architecture/ortho/assets/slap-repair-arthroscopic-CpTAetoL.js",
  "/life-architecture/ortho/assets/slic-subaxial-cervical-spine-injury-classification-W-Gldk8R.js",
  "/life-architecture/ortho/assets/smillie-staging-freiberg-disease-CESkrDo1.js",
  "/life-architecture/ortho/assets/snac-slac-wrist-salvage-ladder-C97JL7r3.js",
  "/life-architecture/ortho/assets/snyder-classification-slap-lesions-DIVQy5mO.js",
  "/life-architecture/ortho/assets/southwick-angle-scfe-severity-B2OL4Xpu.js",
  "/life-architecture/ortho/assets/spinal-deformity-infection-tumor-BmzVfdvx.js",
  "/life-architecture/ortho/assets/spine-trauma-DTWVLLWG.js",
  "/life-architecture/ortho/assets/srs-schwab-classification-adult-spinal-deformity-e6szZM7U.js",
  "/life-architecture/ortho/assets/staged-orif-pilon-fracture-DArxCPC6.js",
  "/life-architecture/ortho/assets/stanmore-triangle-shoulder-instability-CRrdMT0b.js",
  "/life-architecture/ortho/assets/steinberg-classification-osteonecrosis-CapPTWV0.js",
  "/life-architecture/ortho/assets/sternocleidomastoid-release-torticollis-GlITZdN4.js",
  "/life-architecture/ortho/assets/stulberg-classification-perthes-outcome-D-EyzMGJ.js",
  "/life-architecture/ortho/assets/su-classification-periprosthetic-distal-femur-B3RrujH5.js",
  "/life-architecture/ortho/assets/su-classification-periprosthetic-fracture-revision-arthroplasty-DsMYXn7X.js",
  "/life-architecture/ortho/assets/subaxial-cervical-fracture-dislocation-fixation-hfRoBP4_.js",
  "/life-architecture/ortho/assets/superior-capsular-reconstruction-BqmY38bS.js",
  "/life-architecture/ortho/assets/suprapatellar-im-nailing-tibial-shaft-Dq_cXwZI.js",
  "/life-architecture/ortho/assets/surgical-antibiotic-prophylaxis-protocol-D0DbVBwe.js",
  "/life-architecture/ortho/assets/surgical-hip-dislocation-femoral-head-orif-Cv7SMSdt.js",
  "/life-architecture/ortho/assets/synthetic-cartilage-implant-cartiva-hallux-rigidus-WREcn6fA.js",
  "/life-architecture/ortho/assets/talar-neck-fracture-orif-D-VqUViS.js",
  "/life-architecture/ortho/assets/tarsal-coalition-resection-interposition-CIghikGA.js",
  "/life-architecture/ortho/assets/tendinopathies-muscle-ankle-instability-BzUJjPiB.js",
  "/life-architecture/ortho/assets/terrible-triad-sequential-fixation-DVymlMWF.js",
  "/life-architecture/ortho/assets/tfcc-repair-arthroscopic-open-ClwfgxyU.js",
  "/life-architecture/ortho/assets/tha-subtrochanteric-shortening-osteotomy-dysplasia-DetG9UEV.js",
  "/life-architecture/ortho/assets/thoracolumbar-posterior-segmental-fixation-burst-chance-CfeIvcQQ.js",
  "/life-architecture/ortho/assets/tibia-fractures-BcVqGeRN.js",
  "/life-architecture/ortho/assets/tibial-plateau-orif-staged-fixation-C3IMzC8s.js",
  "/life-architecture/ortho/assets/tibial-tubercle-osteotomy-DXsNtyPL.js",
  "/life-architecture/ortho/assets/tietjen-classification-pectoralis-major-rupture-BnzBF2Yy.js",
  "/life-architecture/ortho/assets/tile-ao-classification-pelvic-ring-CHrlJhom.js",
  "/life-architecture/ortho/assets/tlics-thoracolumbar-injury-severity-score-DnCESFgV.js",
  "/life-architecture/ortho/assets/tokuhashi-score-metastatic-spine-disease-C1b5vpo3.js",
  "/life-architecture/ortho/assets/tomita-score-metastatic-spine-disease-BnM9EV5F.js",
  "/life-architecture/ortho/assets/tonnis-classification-hip-dysplasia-pao-DotGNrbM.js",
  "/life-architecture/ortho/assets/tonnis-classification-pediatric-hip-dislocation-DFZ3TJhz.js",
  "/life-architecture/ortho/assets/tonnis-grade-hip-osteoarthritis-DRGoffjv.js",
  "/life-architecture/ortho/assets/torg-pavlov-ratio-cervical-canal-stenosis-Bpskm7Tp.js",
  "/life-architecture/ortho/assets/total-ankle-replacement-vs-arthrodesis-ankle-oa-6PHjbIRg.js",
  "/life-architecture/ortho/assets/total-elbow-arthroplasty-UCjEbitk.js",
  "/life-architecture/ortho/assets/total-hip-arthroplasty-primary-osteoarthritis-OL2u8ULj.js",
  "/life-architecture/ortho/assets/total-knee-arthroplasty-DlxYACeR.js",
  "/life-architecture/ortho/assets/tourniquet-use-extremity-surgery-D8RsZBUl.js",
  "/life-architecture/ortho/assets/tranexamic-acid-administration-protocol-2HbJPQFt.js",
  "/life-architecture/ortho/assets/trapeziectomy-thumb-cmc-arthritis-DFcykJ1J.js",
  "/life-architecture/ortho/assets/trochleoplasty-BYAT1SXv.js",
  "/life-architecture/ortho/assets/tscherne-classification-closed-soft-tissue-injury-CAr6rfJI.js",
  "/life-architecture/ortho/assets/tsukayama-zimmerli-classification-pji-H0mtbN7x.js",
  "/life-architecture/ortho/assets/tt-tg-distance-thresholds-gICEIBGv.js",
  "/life-architecture/ortho/assets/tubiana-classification-dupuytren-disease-B4H6_2U9.js",
  "/life-architecture/ortho/assets/two-portal-posterior-hindfoot-endoscopy-Dx1fWOT_.js",
  "/life-architecture/ortho/assets/two-stage-exchange-arthroplasty-pji-5dk4gQuU.js",
  "/life-architecture/ortho/assets/ulnar-shortening-osteotomy-Ca-PAuSk.js",
  "/life-architecture/ortho/assets/unicompartmental-knee-arthroplasty-B4thmi58.js",
  "/life-architecture/ortho/assets/vancouver-ucs-classification-periprosthetic-femur-fracture-BIa8JPn9.js",
  "/life-architecture/ortho/assets/vascularized-bone-grafting-rotational-osteotomy-osteonecrosis-CZ9vIpre.js",
  "/life-architecture/ortho/assets/verdan-flexor-tendon-zones-Ch4EPc1u.js",
  "/life-architecture/ortho/assets/vertebral-body-tethering-ais-C4Bd9GG7.js",
  "/life-architecture/ortho/assets/volar-locking-plate-distal-radius-eVRLqFge.js",
  "/life-architecture/ortho/assets/vte-prophylaxis-tha-B2Np4OsM.js",
  "/life-architecture/ortho/assets/walch-classification-glenohumeral-oa-BWfFQcYL.js",
  "/life-architecture/ortho/assets/waldenstrom-staging-perthes-disease-qMNCWbGR.js",
  "/life-architecture/ortho/assets/warwick-agreement-fai-syndrome-cX6ESWvL.js",
  "/life-architecture/ortho/assets/watson-classification-slac-snac-wrist-CXbNOtp8.js",
  "/life-architecture/ortho/assets/web-DXD_X0xP.js",
  "/life-architecture/ortho/assets/weber-danis-classification-ankle-fracture-B5pjk6N1.js",
  "/life-architecture/ortho/assets/weil-osteotomy-dmmo-plantar-plate-repair-B1K_80Ww.js",
  "/life-architecture/ortho/assets/weinstein-boriani-biagini-wbb-staging-spine-tumors-CrjsUSu9.js",
  "/life-architecture/ortho/assets/wide-resection-radiation-soft-tissue-sarcoma-DUwHNUrC.js",
  "/life-architecture/ortho/assets/wifi-classification-diabetic-foot-CbpDPgh6.js",
  "/life-architecture/ortho/assets/winquist-hansen-classification-Dwr-x8ph.js",
  "/life-architecture/ortho/assets/wound-closure-dair-prevention-protocol-9Cu7BdGT.js",
  "/life-architecture/ortho/assets/young-burgess-classification-pelvic-ring-s78CQLt7.js"
];
const CACHE_ONLY = [
  
];
const IGNORE = [
  
];

self.addEventListener("install", (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      Promise.all(
        PRECACHE.map((url) =>
          cache.add(new Request(url, { cache: "reload" })).catch((err) => {
            console.warn("[sw] precache failed:", url, err);
          })
        )
      )
    )
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME && key !== DATA_CACHE)
          .map((key) => caches.delete(key))
      );
      await self.clients.claim();
      const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
      for (const client of clients) client.postMessage({ type: "sw-activated" });
    })()
  );
});

const isData = (request) => CACHE_ONLY.some((re) => re.test(request.url));

async function match(request, options) {
  const cache = await caches.open(isData(request) ? DATA_CACHE : CACHE_NAME);
  return cache.match(request, options);
}

async function put(request, response) {
  if (!response || !response.ok || response.type !== "basic") return;
  try {
    const cache = await caches.open(isData(request) ? DATA_CACHE : CACHE_NAME);
    await cache.put(request, response);
  } catch (err) {
    console.warn("[sw] cache put failed:", request.url, err);
  }
}

async function networkFirst(event) {
  const { request } = event;
  try {
    const response = await fetch(request);
    event.waitUntil(put(request, response.clone()));
    return response;
  } catch {
    const cached =
      (await match(request, { ignoreSearch: true })) || (await match(INDEX_URL));
    return cached || Response.error();
  }
}

async function cacheFirst(event) {
  const { request } = event;
  const cached = await match(request);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    event.waitUntil(put(request, response.clone()));
    return response;
  } catch {
    return Response.error();
  }
}

async function staleWhileRevalidate(event) {
  const { request } = event;
  const cached = await match(request);
  const network = fetch(request).then(
    (response) => {
      event.waitUntil(put(request, response.clone()));
      return response;
    },
    () => null
  );
  if (cached) {
    event.waitUntil(network);
    return cached;
  }
  return (await network) || Response.error();
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(SCOPE_PATH)) return;
  if (IGNORE.some((re) => re.test(url.pathname))) return;
  // Partial responses (206) cannot be cached; leave media range requests to the network.
  if (request.headers.has("range")) return;

  if (request.mode === "navigate") {
    event.respondWith(networkFirst(event));
  } else if (url.pathname.includes("/assets/") || CACHE_ONLY.some((re) => re.test(url.href))) {
    event.respondWith(cacheFirst(event));
  } else {
    event.respondWith(staleWhileRevalidate(event));
  }
});
