import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const STATIC_FILES = ["", "index.html", "manifest.json", "icon-192.png", "icon-512.png"];

const toRegex = (r) => (r instanceof RegExp ? r : new RegExp(r));

function resolveUrl(base, p) {
  if (/^(https?:)?\/\//.test(p) || p.startsWith("/")) return p;
  return base + p.replace(/^\.\//, "");
}

const reList = (list) =>
  list.map((r) => `new RegExp(${JSON.stringify(r.source)}, ${JSON.stringify(r.flags)})`).join(",\n  ");

function workerSource({ cacheName, prefix, base, precache, cacheOnly, ignore }) {
  return `/* Generated by packages/shared/vite/swPlugin.js. Do not edit. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const CACHE_PREFIX = ${JSON.stringify(prefix)};
// Large cache-only files (engine nets, game databases) live in a cache that
// survives deploys; only the per-build cache is replaced on activate.
const DATA_CACHE = CACHE_PREFIX + "data";
const INDEX_URL = new URL(${JSON.stringify(base + "index.html")}, self.location).href;
const SCOPE_PATH = new URL(self.registration.scope).pathname;
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const CACHE_ONLY = [
  ${reList(cacheOnly)}
];
const IGNORE = [
  ${reList(ignore)}
];

self.addEventListener("install", (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      Promise.all(
        PRECACHE.map((url) =>
          cache.add(new Request(url, { cache: "reload" })).catch((err) => {
            console.warn("[sw] precache failed:", url, err);
          })
        )
      )
    )
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME && key !== DATA_CACHE)
          .map((key) => caches.delete(key))
      );
      await self.clients.claim();
      const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
      for (const client of clients) client.postMessage({ type: "sw-activated" });
    })()
  );
});

const isData = (request) => CACHE_ONLY.some((re) => re.test(request.url));

async function match(request, options) {
  const cache = await caches.open(isData(request) ? DATA_CACHE : CACHE_NAME);
  return cache.match(request, options);
}

async function put(request, response) {
  if (!response || !response.ok || response.type !== "basic") return;
  try {
    const cache = await caches.open(isData(request) ? DATA_CACHE : CACHE_NAME);
    await cache.put(request, response);
  } catch (err) {
    console.warn("[sw] cache put failed:", request.url, err);
  }
}

async function networkFirst(event) {
  const { request } = event;
  try {
    const response = await fetch(request);
    event.waitUntil(put(request, response.clone()));
    return response;
  } catch {
    const cached =
      (await match(request, { ignoreSearch: true })) || (await match(INDEX_URL));
    return cached || Response.error();
  }
}

async function cacheFirst(event) {
  const { request } = event;
  const cached = await match(request);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    event.waitUntil(put(request, response.clone()));
    return response;
  } catch {
    return Response.error();
  }
}

async function staleWhileRevalidate(event) {
  const { request } = event;
  const cached = await match(request);
  const network = fetch(request).then(
    (response) => {
      event.waitUntil(put(request, response.clone()));
      return response;
    },
    () => null
  );
  if (cached) {
    event.waitUntil(network);
    return cached;
  }
  return (await network) || Response.error();
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(SCOPE_PATH)) return;
  if (IGNORE.some((re) => re.test(url.pathname))) return;
  // Partial responses (206) cannot be cached; leave media range requests to the network.
  if (request.headers.has("range")) return;

  if (request.mode === "navigate") {
    event.respondWith(networkFirst(event));
  } else if (url.pathname.includes("/assets/") || CACHE_ONLY.some((re) => re.test(url.href))) {
    event.respondWith(cacheFirst(event));
  } else {
    event.respondWith(staleWhileRevalidate(event));
  }
});
`;
}

export function sharedSw({ name, extraPrecache = [], cacheOnly = [], skipPrecache = [], ignore = [] } = {}) {
  if (!name) throw new Error("sharedSw: `name` is required");
  const cacheOnlyRe = cacheOnly.map(toRegex);
  const skipRe = skipPrecache.map(toRegex);
  const ignoreRe = ignore.map(toRegex);
  let base = "/";
  let outDir = "dist";
  let assetsDir = "assets";
  let disabled = false;
  let generated = null;

  return {
    name: "shared-sw",
    apply: "build",
    configResolved(config) {
      base = config.base || "/";
      if (!base.endsWith("/")) base += "/";
      outDir = path.resolve(config.root, config.build.outDir);
      assetsDir = config.build.assetsDir || "assets";
      disabled = config.mode === "android" || Boolean(config.build.ssr);
    },
    generateBundle(_options, bundle) {
      if (disabled) return;
      const names = Object.keys(bundle).sort();
      const emitted = names.filter((f) => f.startsWith(assetsDir + "/"));
      const precache = [
        ...new Set([...STATIC_FILES, ...emitted, ...extraPrecache].map((p) => resolveUrl(base, p))),
      ].filter((url) => !skipRe.some((re) => re.test(url)));
      const hash = createHash("sha1")
        .update([...names, ...extraPrecache].join("\n"))
        .digest("hex")
        .slice(0, 8);
      generated = workerSource({
        cacheName: `${name}-${hash}`,
        prefix: `${name}-`,
        base,
        precache,
        cacheOnly: cacheOnlyRe,
        ignore: ignoreRe,
      });
    },
    closeBundle() {
      if (disabled || !generated) return;
      fs.mkdirSync(outDir, { recursive: true });
      // Overwrites any stale sw.js copied from public/.
      fs.writeFileSync(path.join(outDir, "sw.js"), generated);
      generated = null;
    },
  };
}
